#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Fix Android Studio - Gradle Processes
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🤖
# @raycast.packageName Developer Utils
# @raycast.needsConfirmation true

# Documentation:
# @raycast.description Will stop all Gradle processes created by Android Studio

echo "Stopping all Gradle Processes created by Android Studio"

gradle --stop

echo "Gradle processes stopped"



